### ISSUE TITLE
php in html-attributes require mthaml in runtime

### ISSUE THREAD

**Issue by javoire** [alexluke/grunt-haml-php#6]
According to MtHaml docs (https://github.com/arnaud-lb/MtHaml), this:

```
%ul#users
  - foreach($users as $user)
    %li.user
      = $user->getName()
      Email: #{$user->getEmail()}
      %a(href=$user->getUrl()) Home page
```

Is supposed to become this:

```
<ul id="users">
  <?php foreach($users as $user) { ?>
    <li class="user">
      <?php echo $user->getName(); ?>
      Email: <?php echo $user->getEmail(); ?>
      <a href="<?php echo $user->getUrl(); ?>">Home page</a>
    </li>
  <?php } ?>
</ul>
```

However, using grunt-haml-php, I get this:

```
<ul id="users">
  <?php foreach($users as $user) { ?>
    <li class="user">
      <?php echo $user->getName(); ?>
      Email: <?php echo $user->getEmail(); ?>
      <a <?php echo MtHaml\Runtime::renderAttributes(array(array('href', ($user->getUrl()))), 'html5', 'UTF-8'); ?>>Home page</a>
    </li>
  <?php } ?>
</ul>
```

The href attribute on the a-tag requires MtHaml at runtime. I don't if this is what you're referring to here #3. 

Is there a possibilty to change this behaviour? I'm sooo close now to not having to use regular ugly php and html so I'd be so thrilled if was possible.

Cheers
Jonatan

**Comment by esad** [comment]
@ezekg Thanks for this patch, I've just made a PR for `grunt-haml-php` to accept and pass enableDynamicAttributes option to the new version of MtHaml

@alexluke Do you mind giving it a look?

**Comment by alexluke** [comment]
Thanks everyone, 0.4.1 is now available on npm with this option.
